name: hive_generator
description: Extension for Hive. Automatically generates TypeAdapters to store any class.
version: 2.0.1
homepage: https://github.com/hivedb/hive
documentation: https://docs.hivedb.dev/

environment:
  sdk: '>=3.7.0 <4.0.0' 

dependencies:
  build: ^3.0.0
  source_gen: ^3.0.0
  hive: ^2.2.3
  analyzer: ^6.9.0
  dartx: ^1.1.0

dev_dependencies:
  test: ^1.16.0
  build_test: any
  build_runner: any
  lints: ^2.0.0
